sudo: required
services:
  - docker

before_install:
  - docker build -t nicomness/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -t nicomness/docker-react npm run test -- --coverage